# Generated by Django 5.2.1 on 2025-05-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mess_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messName', models.CharField(max_length=100)),
                ('mounthName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('managerName', models.CharField(max_length=50)),
            ],
        ),
    ]
