# Generated by Django 5.2.1 on 2025-05-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess_details',
            name='managerName',
        ),
    ]
