# Generated by Django 5.2.1 on 2025-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0002_remove_mess_details_managername'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculate_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMounthlyCost', models.IntegerField(max_length=100)),
                ('totalMeal', models.IntegerField(max_length=50)),
                ('aditonalCost', models.IntegerField(max_length=100)),
                ('managerName', models.CharField(max_length=50)),
            ],
        ),
    ]
