# Generated by Django 5.2.1 on 2025-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0003_calculate_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate_cost',
            name='mealCharge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='aditonalCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='totalMeal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='totalMounthlyCost',
            field=models.IntegerField(default=0),
        ),
    ]
