# Generated by Django 5.2.1 on 2025-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0005_alter_calculate_cost_mealcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate_cost',
            name='mealCharge',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
