# Generated by Django 5.2.1 on 2025-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0006_alter_calculate_cost_mealcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boder_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoderName', models.CharField(max_length=50)),
                ('BoderMeal', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('ShafBill', models.IntegerField(default=0)),
                ('WifiBill', models.IntegerField(default=0)),
                ('DustBill', models.IntegerField(default=0)),
                ('ReciveMoney', models.IntegerField(default=0)),
                ('BoderAdditionalCost', models.IntegerField(default=0)),
            ],
        ),
    ]
