# Generated by Django 5.2.1 on 2025-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0007_boder_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='boder_details',
            name='BoderMealCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boder_details',
            name='BorderTotalCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boder_details',
            name='Deu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boder_details',
            name='Return',
            field=models.IntegerField(default=0),
        ),
    ]
