# Generated by Django 5.2.1 on 2025-08-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0008_boder_details_bodermealcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mess_details',
            name='mounthName',
        ),
        migrations.AddField(
            model_name='mess_details',
            name='date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='boder_details',
            name='managerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
        migrations.AddField(
            model_name='mess_details',
            name='managerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='managerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
    ]
