# Generated by Django 5.2.1 on 2025-08-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0009_mess_manager_remove_mess_details_mounthname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate_cost',
            name='managerName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='mess_details',
            name='managerName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
    ]
