# Generated by Django 5.2.1 on 2025-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0010_alter_calculate_cost_managername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_details',
            name='date',
            field=models.DateField(max_length=20),
        ),
    ]
