# Generated by Django 5.2.1 on 2025-08-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0011_alter_mess_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate_cost',
            name='managerName',
        ),
    ]
