# Generated by Django 5.2.1 on 2025-08-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0012_remove_calculate_cost_managername'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate_cost',
            name='managerName',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='mess_details',
            name='managerName',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mmssapp.mess_manager'),
        ),
    ]
