# Generated by Django 5.2.1 on 2025-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0013_calculate_cost_managername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField(max_length=16)),
            ],
        ),
    ]
