# Generated by Django 5.2.1 on 2025-08-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0014_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boder_details',
            name='managerName',
        ),
        migrations.RemoveField(
            model_name='calculate_cost',
            name='managerName',
        ),
        migrations.AddField(
            model_name='boder_details',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='mmssapp.mess_manager'),
        ),
        migrations.AddField(
            model_name='boder_details',
            name='mess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='mmssapp.mess_details'),
        ),
        migrations.AddField(
            model_name='calculate_cost',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='mmssapp.mess_manager'),
        ),
        migrations.AddField(
            model_name='calculate_cost',
            name='mess',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='mmssapp.mess_details'),
        ),
        migrations.AlterField(
            model_name='mess_details',
            name='managerName',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mess', to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='password',
            field=models.IntegerField(),
        ),
    ]
