# Generated by Django 5.2.1 on 2025-08-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0015_remove_boder_details_managername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boder_details',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='boder_details',
            name='mess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders', to='mmssapp.mess_details'),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='mmssapp.mess_manager'),
        ),
        migrations.AlterField(
            model_name='calculate_cost',
            name='mess',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='mmssapp.mess_details'),
        ),
        migrations.AlterField(
            model_name='mess_details',
            name='managerName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mess', to='mmssapp.mess_manager'),
        ),
    ]
