# Generated by Django 5.2.1 on 2025-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmssapp', '0016_alter_boder_details_manager_alter_boder_details_mess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate_cost',
            name='aditonalCost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
